version: '3.4'

services:
  seq:
    image: datalust/seq:2023

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest

  pgsql-server:
    image: postgres:16

  mongo-server:
    image: mongo:6

  redis-server:
    image: redis:7.2.1

  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine

  identity-api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/IdentityAndUserManagement/Identity.API/Dockerfile
    depends_on:
      - mssql-server
      - seq

  usermanagement-api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: .
      dockerfile: Services/IdentityAndUserManagement/UserManagement.API/Dockerfile
    depends_on:
      - mssql-server
      - mongo-server
      - seq